* Development in Siconos/Numerics
** VI methods
   + Projection Contraction techniques ==>  in Fixed point VI
   + Prediction Correction type Extragradient ==> in Extragradient   He.Liao_JOTA2002   Noor_CMA2002 Algo 3.8 of Noor_JOTA2003
   + Two-step forward–backward splitting-type algorithms Noor_CMA1999 Noor_MCM1999
     + Forward--backward splitting de Tseng.
** Newton method based on SOCCP formulation
** General SOCCP solver
+ Interior points methods
  + Work of Kleinert, Simeon and Obermayr
  +    
+ FB and regularized FB for SOCCP
+ Have a look to cvxopt (python and C)
** Proximal point algorithm
+ Continue to study the influence of the regularization parameter
** LocalAlartCurnier
+ Possibility to avoid the LU factor of W ?
+ Guess rho with VIFixedPointProjection
** Krylov techniques
+ Work of Heyn et al.
** Acceleration of Gauss-Seidel Strategy
+ Aitken--like strategy
+ have a look to FISTA and Nesterov work. INPPA
** ACLM formulation.
+ Implement Fixed point Iteration
  + Which internal solver ? 
    + the internal solver must use the convexity of the problem SOCQP ?
    + Block-splitting + local solver (PSOR + list of solver). Copy of nsgs with psor options DONE
    + Remain to add Newton--based solver ?
+ ACLM with SOCLCP solver
  + What is the good strategy for the internal solver ?
    very accurate convergence or  loose ONE
      
+ Newton method of convex SOCLCP or SOCQP
  Newton method on the problem $F(s)=s$

*** TODO Alternative strategy to drive to convergence. ?

* Literature
  Check for ``solving frictional contact problem''
  \begin{itemize}
  \item in google, and scholar
  \item Zentralblatt and MAthSciNet
  \end{itemize}
** Renard
   add [[http://math.univ-lyon1.fr/~renard/papers/2008_frst.pdf]] in the list of reading
** Read work of Kucera Dostal
** CCP / SOCP
*** Read Goldfarb Alizabeh
*** SOCCP Fukushima, Hyashi Works
+  [[/Users/acary/Publi/Optimisation/SOCCP]]
+ Combined and smoothing method
+ Matrix splitting

*** Christian Kanzow, Izabella Ferenczi, and Masao Fukushima
    ON THE LOCAL CONVERGENCE OF SEMISMOOTH NEWTON METHODS FOR LINEAR AND NONLINEAR SECOND-ORDER CONE PROGRAMS WITHOUT STRICT COMPLEMENTARITY∗
    [[/Users/acary/Publi/Optimisation/SOCCP/Kanzow.Ferenczi.Fukushima_SIOPT2009.pdf]]

*** Smoothing and BFGS work of Chen and Tseng
  +  [[/Users/acary/Publi/Optimisation/SOCCP/Chen.Tseng_MP2005.pdf]]
  + retrieve L-BFGS of Nocedal  ?  Use of M1QN3 ?
*** SOCLCP

** Existing software
*** SOCP: Software for Second-Order Cone Programming
	 M. Lobo, L. Vandenberghe, and S. Boyd
	 http://stanford.edu/~boyd/old_software/SOCP.html
*** RESNA :
*** COMPASS: A Free Solver for Mixed Complementarity Problems
    D. A. Schmelzer
    http://www.mat.univie.ac.at/~neum/software/compass/schmelzerDA.pdf
** Extra gradient method and De Saxce Fixed point
   The value of the parameter strongly influences the convergence.
  + An implementation is present in the routine. What is the source ?
  + Adaptive step-size rule.
    + Marcotte and Wu 1995 (see LNACM 35)
      Too theoritic.
    + Book of Konnov
      http://www.springer.com/business+%26+management/operations+research/book/978-3-540-67999-8?token=gbgen&wt_mc=Google-_-Book%20Search-_-Springer-_-EN
      + Have a look to On the Goldstein - Levitin - Polyak Gradient
     Projection Method DIMITRI P. BERTSEKAS for a justification on the generalized Armijo step rule
      [[/Users/acary/Publi/Optimisation/Bertsekas_IEEETAC1976.pdf]]
    + Khobotov_CMMP1987
      Modification of the extra-gradient method for solving variational inequalities and certain optimization problems.
      /Users/acary/Publi/Optimisation/VariationalInequalities/Khobotov_CMMP1987.pdf
      --> First  implementation of an Armijo rule for EG method.
    + Solodov.Tseng1996, Han.Lo_CMA2002.
            
      Two New Self-Adaptive Projection Methods for Variational Inequality Problems  Han Lo CMA 2002
      [[/Users/acary/Publi/Optimisation/VariationalInequalities/Han.Lo_CMA2002.pdf]]

      [[/Users/acary/Publi/Optimisation/VariationalInequalities/Solodov.Tseng_SICOPT1996.pdf]]
      
      --> Armijo step-size rule with differents criteria for the Lipschitz condition.
    + He.Liao_JOTA2002
      [[/Users/acary/Publi/Optimisation/VariationalInequalities/He.Liao_JOTA2002.pdf]]
      --> Armijo step-size rule with differents criteria for the Lipschitz condition.
      --> Prediction--Correction type Method
    + Chen.ea_EJOR2001
      A self-adaptive self-adaptive projection and contraction algorithm for the traffic assignment problem with path-speci®c costs projection and contraction algorithm for the trac assignment problem with path-speciic costs  
      [[/Users/acary/Publi/Optimisation/VariationalInequalities/Chen.ea_EJOR2001.pdf]]
      --> Application of Projection and contraction methods to traffic assignment problem
    + Han_JCAM2008
      A generalized proximal-point-based prediction–correction method for variational inequality problems
      [[/Users/acary/Publi/Optimisation/VariationalInequalities/Han_JCAM2008.pdf]]
      --> A generalized proximal-point-based prediction–correction algorithm.  
      --> Use a Bregman function to compute generalization of Proximal algorihtm
      (see  Chen.Teboublle_SIOPT1993  [[/Users/acary/Publi/Optimisation/Chen.Teboulle_SIOPT1993.pdf]])
    + Liao.Wang_CMA2002, Han_AMC2006
      --> Projection and contraction methods with a given sequence t_k Classical Cauchy method
      --> seems not to have a real interest for us
    + Han.Sun_CMA2008
      --> rule for Lipschitz constant inverse of Solodov !!
    + Noor_JOTA2003
      [[/Users/acary/Publi/Optimisation/VariationalInequalities/Noor_JOTA2003.pdf]]
      + discussion on inertial proximal method.
	ALVAREZ, F., and ATTOUCH, H., An Inertial Proximal Method for Maximal
        Monotone Operators ûia Discretization of a Nonlinear Oscillator with Damping,
	Set-Valued Analysis, Vol. 9, pp. 3–11, 2001.
      + long review of various algorithm
	+ Algo 3.1. Fixed point
	+ Algo 3.2. Inertial proximal method.
	+ Algo 3.3. Extragradient method
	+ Algo 3.4. Extragradient method with Wiener Hopf (Projection correction) He.Liao_JOTA2002
	  
	+ Algo 3.5. Prediction--Correction type extragradient. bvery similar to previous one Noor_CMA2002
	+ Algo 3.6. Two-step forward–backward splitting-type algorithms Noor_CMA1999 Noor_MCM1999
	+ Algo 3.7. Self-adaptative version of 3.6
	+ Algo 3.8. unified extragradient type method.
	  contains 3.4 

    + Wang.ea_JOTA2001
      Unified framework of extragradient-type methods for pseudomonotone variational inequalities
      YJ Wang, NH Xiu, CY Wang - Journal of Optimization Theory and …, 2001 - Springer
    
      
    + D.F. Sun, A new step-size skill for solving a class of nonlinear projection equations, Journal of Computational Mathematics 13, 357-368, (1995).
      [[/Users/acary/Publi/Optimisation/VariationalInequalities/Sun_JCAM95.pdf]]
      
==> Retrieve
NOOR, M. A., A Modified Extragradient Method for General Monotone Vari-
ational Inequalities, Computers and Mathematics with Applications, Vol. 38, pp.
19–24, 1999.

NOOR, M. A., New Extragradient-Type Methods for General Variational
Inequalities, Journal of Mathematical Analysis and Applications, Vol. 277,
pp. 379–395, 2002.

NOOR, M. A., Some Algorithms for General Monotone Mixed Variational
Inequalities, Mathematics and Computer Modelling, Vol. 29, pp. 1–9, 1999.

IUSEM, A. N., and SVAITER, B. F., A Variant of Korpeleûich’s Method for Vari- ational Inequalities with a New Search Strategy, Optimization, Vol. 42, pp. 309– 321, 1997.

2. SOLODOV, M. V., and SVAITER, B. F., A New Projection Method for Variational Inequality Problems, SIAM Journal on Control and Optimization, Vol. 37, pp. 765–776, 1999.


** Proximal point algorithms
  + Chen.Teboublle_SIOPT1993
    [[/Users/acary/Publi/Optimisation/Chen.Teboulle_SIOPT1993.pdf]]
  + ALVAREZ, F., and ATTOUCH, H., An Inertial Proximal Method for Maximal
     Monotone Operators ûia Discretization of a Nonlinear Oscillator with Damping,
     Set-Valued Analysis, Vol. 9, pp. 3–11, 2001.
  + A new proximal-based globalization strategy for the Josephy-Newton method for variational inequalities
    Optimization Methods and Software (Impact Factor: 1.21). 01/2002; 17(5). 
    Solodov Svaiter

** TODO Have a look to paper about a Gauss-Newton
   approach with quite elaborate line search:
   http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=5509

** Target journal Archives of Computational Methods in Engineering
   http://www.springer.com/engineering/computational+intelligence+and+complexity/journal/11831

   extended state-of-the-art reviews
** Optimization
+ [[http://www.optimization-online.org/DB_FILE/2011/12/3266.pdf]]
+ http://www.optimization-online.org/DB_HTML/2012/01/3302.html
  [[/Users/acary/Desktop/Lopez.ea_OO2012.pdf]]
  Definition des operateurs copositive
** QVI implementation
  + Work of Facchinei (Singapore Talk)
  + Work of Michael Ulbrich (Singapore Talk)
** Augmented Lagrangian formulation
+ Discuss with Paul Armand
   
** I.N. Doudoumis, E.N. Mitsopoulou, G.N. Nikolaidis
A comparative numerical study on the unilateral contact problem with friction
Proceedings of the 1st National Congress of Computational Mechanics, Athens (1992)

@article{
year={1975},
issn={0020-1154},
journal={Ingenieur-Archiv},
volume={44},
number={6},
doi={10.1007/BF00534623},
title={A nonlinear programming approach to the unilateral contact-, and friction-boundary value problem in the theory of elasticity},
url={http://dx.doi.org/10.1007/BF00534623},
publisher={Springer-Verlag},
author={Panagiotopoulos, P.D.},
pages={421-432},
language={English}
}
     

* Comparison tools

** using comp
   
+ parallel usage
  ls *.hdf5 | parallel comp.py --timeout=100 --no-collect '--file={}'
+ --no-collect   
  leave the result into separate file that are named according the solver and the name of the problem
+ --just--collect
  collect all the result into comp.hdf5
+ --timeout=10   
  set the maximum time of computation for a solver to 10 seconds
+ --domain='a:d:b'
  restrict the domain of the performance profile to the interval [a,b] with a step of d
  or a perfomance profile a should be greater or equal 1
+ --iter  OBSOLETE ?
  select the number iteration as the measure for the perfomance profile
+ --time OBSOLETE ?
  select the computation time as the measure for the perfomance profile
+ --flop OBSOLETE ?
+ --measure=value
  select the value  as the measure for the perfomance profile
  possible values are time, iter, flpops


+ usage

  comp.py   --display --time --domain='1:0.1:10'  comp.hdf5


comp.py --display --measure=time --solvers=Gauss,Tresca,SOCLCP,ACLM --domain=1:0.1:100



* Paper contact-friction 					  :ABC:PAPER:
** Objectives
   + Simple iteratives  methods
     + Fixed point
     + Projection/splitting (PSOR)
     + Fake Coulomb Friction (Anitescu \& Tasora)
   + Complementarity function (zeroes of functions)
     + Alart--Curnier method
     + Jean--Moreau method
     + DeSaxce + Newton (Joli Feng)
     + Fischer--bursmeister for SOCCP (smoothing hayashima fukushima)
     + Newton
       + line search (GP, Armijo, Non-monotone watch dogs)
   + Optimisation-based methods
     + Successive approximations (Haslinger, ...) QP et SOC (Kucera)
     + ACLM (Fixed point, Newton, Quasi-Newton, ....)
     + SOCLCP (Kanno, et al.)
   + Optional approach
     + SOCP (Optimization approach)
     + Interior point
** Beyond the scope of the paper.
   + no LCP
   + no pivoting
** Monotonicity of VI

{\blue 

\paragraph{monotonicity}

For Problem~\ref{prob:II},%  we have the VI (\ref{eq:vi-II}) that we rewrite for our convenience with
% \begin{equation}
%   \label{eq:vi-II}
%   F_{\vitwo}(u,r) =\left[
%   \begin{array}{c}
%     u - Wr -q
%     u + g(u)
% \end{array}\right]
% \text{ and } X_{\vitwo} = \RR^{n_c}\times K.
% \end{equation}
% \begin{equation}
%   \label{eq:mono-IIa}
%     (F_{\vitwo}(u,r)-F_{\vitwo}(v,s))^T(
%     \left[\begin{array}{c}
%         u \\ r
%     \end{array}\right]
% -
%  \left[\begin{array}{c}
%         v \\ s
v%     \end{array}\right]
% ) = (r-s)^T W (r-s)   + \|u-v\|^2 + \sum _{\alpha =1}^{n_c} \mu^\alpha (x_\n-y_n) [\|[Wx+q]^\alpha_\t \| - \|[Wy+q]^\alpha_\t \|]
% \end{equation}





\begin{equation}
  \label{eq:mono-II}
    (F_{\vitwo}(x)-F_{\vitwo}(y))^T(x-y) = (x-y)^T W (x-y) + \sum _{\alpha =1}^{n_c} \mu^\alpha (x_\n-y_n) [\|[Wx+q]^\alpha_\t \| - \|[Wy+q]^\alpha_\t \|]
\end{equation}

\begin{equation}
  \label{eq:Jac-II}
    \nabla_r F_{\vitwo}(r) = W + W\left[
    \begin{array}{cc}
       0 & \mu \Frac{[W r+q]_\t}{\|[W r+q]_\t\|}\\
       0 & 0
    \end{array}\right]
\end{equation}

** Tests problems (FCLIB)
   + collections
     + spheres
       + flows and stacking (Example Tasora)
     + sticks
       + flows and stacking (Example Tasora)
     + hair, LMGC clumps ??
   + deformables quasi-static / dynamic
     + Hertz 3D FEM
     + masonry

** POSTPONED Redaction article ABH
   CLOSED: [2016-03-20 Sun 21:48] DEADLINE: <2015-11-08 Sun>
   + Complete the introduction
     + Add a list of approach not discussed in the paper. leave it as future work.
   + Complete Section 3
     + Understand the continuity argument of Alart
     + Find references for alternating projection N and after T
   + Complete Section 4
     + Section 4.1
       \begin{itemize}
       \item situate the work of \cite{DeSaxce.Feng90,DeSaxce.Feng1998}
           and  \cite{Simo.Laursen1992,Laursen.Simo1993b}.
       \item implement the work of Simo just to laugh
       \item Have a careful look to the work of Krause.
       \end{itemize}
     + Section 4.2
       \begin{itemize}
       \item Rule and efficient Choice of $\rho$.
       \item Should we remove hyperplane projection ?
       \item Acceleration techniques and Nesterov Method ? FISTA and Nesterov work. INPPA
       \end{itemize}
     + Section 4.3
       What can be retained from\cite{Heyn_PhD2013} ?
       Krylov techniques
 

** Meeting <2015-12-04 Fri>
   MB, VA
+ Methods:
  + NSN : Technical report on Jacobians computation
  + NSN : regularization approach, computation of \rho
  + PROX :  Try to find a all--terrain strategy, Hager, FISTA, INPPA
  + Try to think alll remaining approach to develop : ACLM+NSN, TRESCA+?, BFGS, Options N after T
+ Tests
  + Rerun all the tests on Luke to get a full-test.pdf
  + Plan a meeting to discuss the conclusion to draw of the document (redo, check, conclude, ...)

    
** Meeting <2016-03-07 Mon>
   MB, VA, OH 

+ Journals
  + CMAME http://www.journals.elsevier.com/computer-methods-in-applied-mechanics-and-engineering/
  + IJNME [[http://onlinelibrary.wiley.com/journal/10.1002/(ISSN)1097-0207]]
  + ACME Archives of Computational Methods in Engineering

+ Solvers
  + VI : FixedPoint, ExtraGradient, Hyperplane
    
  + Nonsmooth Newton (NSN)
    + Validation of gradients: 
      - AlartCurnier, JeanMoreau OK
      - Natural map, Fischer Burmeister: stability problem
    + Line search does not seem that help at all
      - 
  + Hybrid
    + Predconditioning NSN by a VI solvers.

  + Interior Point (IP)
    + does not work that well -> remove?

+ Conclusion :
  + NSN.
    + Difficulty related to the computation of gradients for FB and Natural 
  + Hyperstaticity : 
    + All the NSN fails.
    + NSGS supersedes. 
    + PROX may improve the situation. 
    + VI not so bad in view of parrelism
  + KerH trivial (flexible) (Cube_H8)
    + NSN supersedes
    + Line search does not help much (nonmonotone version?)
    + JM and AC work better -> analyse this maybe from an Augmented Lagrangian perspective



** Meeting <2016-03-17 Thu>
   MB, VA, OH.

   + MB: new generatation of the gradient
     + Jean Moreau, Alart Curnier, k
     + Natural map. pb de division par la norme de x_t
     + VA: Scaling Nesterov Todd

   + VA: Why nothing on Interior points?

   + OH:
     + Remark on the introduction. restructuration
     + Delete problem I
     + Notation des variables


** Meeting <2016-03-31 Thu>
   + MB : natural map correct. meme chose pour le Fisher
   + OH:  remark sur le papier.
     



** Meeting <2016-04-20 Wed>

+ MB
  + clean gradients in the tex file. AC Natural Map
  + killed job on luke.ciment ?
  + swig version 2.11
+ VA




** TODO List of actions.  Last update <2016-06-16 Thu>
   DEADLINE: <2016-04-04 Mon>

   + Paper. General Work :
     + All sections : Clean redaction note and report here the items  :VA:

     + Complete the introduction
       + Add a list of approach not discussed in the paper. leave it as future work.
       + Detail where it is possible why some approaches are not discussed (IPM)

     + Section 3.
       + Understand the continuity argument of Alart (V.A., O.H.)
       + Find references for alternating projection N and after T (V.A)
       + Section 3.3 Remork to send the maximum in Appendix (V.A.)
       + NDRVA 3.3 Comment of Olivier ? (O.H.)
       + Discuss remark about smoothing
       + Section 3.4 in Appendix.
       + NDRVA 3.5 Remark Olivier ?
 
     + Section 4.
       + Section 4.1
	 \begin{itemize}
	 \item Have a careful look to the work of Krause.
	 \end{itemize}
       + NDROH 4.1 :  to be discussed (V.A. O.H.)
       + Section 4.2
	 \begin{itemize}
	 \item Should we remove hyperplane projection ?
	 \item Acceleration techniques and Nesterov Method ? FISTA and Nesterov work. INPPA
	 \end{itemize}
	 NRDOH  4.3 4.4 To be discussed, not so clear for me.
       + Further work
	 + What can be retained from\cite{Heyn_PhD2013} ?
	   + Krylov techniques
	 + cite somewhere~\citep{Laborde.Renard_MMAS2008}
	 + Have a careful look to the work of Krause.
         + Implement the FP-QVI-MJ and FP-QVI-AC within the De Saxce approach ? Useful ?
     
     + Section 5. 
       + Section 5.2 
	 + In~\cite{Hayashi.ea_SIOPT2005}, spectral decomposition of the projection + smoothing.  semi-smooth Newton method
	 + Choice of $\rho_\n$ $\rho_\t$. Discussion paper Alart~\citep{Alart1993} or \citep{Jourdan.Alart.ea98}.
	 + Is the proj formulation better than FB for all the reason related to the augmented Lagrangian approach ?
	 + See~\cite{Mirar.Arora_SMO2004-I} for an automatic adaption of the penalization coefficient ? Link woth the work of Armand
       + Section 5.3 TBW 
	 + question about the naming convention : FBLSA ?

     + Section 6
       + Section  6.1
	 + Situate~\cite{Hayashi.ea_JCAM2005}
	 + Acceleration technique. Aitken acceleration. Lebon, Raous et al.
           contractive sequence transformations in 
           C. Brezinski et M. Redivo-Zaglia, Extrapolation Methods, Theory and Practise, North- Holland, Amsterdam, 1992.
           J.P. Delahaye, Sequence transformations, Springer Verlag, Berlin, 1988.
       + Section 6.2 Work on the proximal point.
	 
     + Section 7. (Optimization)
       + Alternating ?
       + ACML
       + SOCCP

     + Misc.
       + Where to write the formulation of hybrid Solvers :VA:
       + Investigate the best journal to submit (and format) :VA:
       + Fixes + new parts in paper :OH:


   + Devel and comparisons:    
     + Rerun computation  :MB:
     + Fclib. Thinking of howto bind with Matlab :OH:
     + Fclib and swig python tranlastion :MB:
     + Add a small description file for example directory. texfile img profile. :VA:
     + Add description in fclib report. :VA:
     + Update and correct naming for the line-searches. FBLSA  :MB:OH:
     + Merge line--searches procedures :MB:OH:
       
