#!/bin/bash

#OAR --project siconos
#OAR --name siconos-siab-comp
#OAR -l /nodes=1/cpu=1/core=4,walltime=48:00:00 

. $HOME/.profile
exec guix environment --pure --ad-hoc --pure -m ./siconos-manifest.scm which sed findutils tar gzip gdb siconos@4.3:debug siconos@4.3 --with-source=$HOME/src/siconos -- /bin/sh -c "OAR_JOB_ID=$OAR_JOB_ID OAR_NODE_FILE=$OAR_NODE_FILE $HOME/src/faf/scripts/SpheresInABox/run-admm-mpi-siab.1e-1.7000"
